<?php

class ProductsCategoryMenuWalker extends Walker_Nav_Menu
{
    function start_lvl(&$output, $depth = 0, $args = array())
    {
        $indent = str_repeat("\t", $depth);
        $classNames = "dropdown-menu";
        $output .= "\n$indent<ul class=\"$classNames\">\n";
    }

    function end_lvl(&$output, $depth = 0, $args = array())
    {
        $indent = str_repeat("\t", $depth);
        $output .= "$indent</ul>\n";
    }

    function start_el(&$output, $item, $depth = 0, $args = null, $id = 0)
    {
        $indent = ( $depth ) ? str_repeat( "\t", $depth ) : '';

        $classes = empty ( $item->classes ) ? [] : (array) $item->classes;
        $classes[] = ($this->has_children) ? 'dropdown' : '';

        $classNames =  join(' ', apply_filters('nav_menu_css_class', array_filter( $classes ), $item, $args ) );
        $classNames = esc_attr($classNames);

        $output .= "\n$indent<li class=\"nav-item $classNames\">\n";

        $attributes = ! empty( $item->attr_title ) ? ' title="' . esc_attr($item->attr_title) . '"' : '';
        $attributes .= ! empty( $item->target ) ? ' target="' . esc_attr($item->target) . '"' : '';
        $attributes .= ! empty( $item->xfn ) ? ' rel="' . esc_attr($item->xfn) . '"' : '';
        $attributes .= ! empty( $item->url ) ? ' href="' . esc_attr($item->url) . '"' : '';

        $itemClasses = [];
        // For active class
        if ($item->current || $item->current_item_ancestor) {
            $itemClasses[] = 'active';
        }
        // For parent
        if ($depth < 1) {
            $itemClasses[] = 'nav-link';
        }
        // For children
        else {
            $itemClasses[] = 'dropdown-item';
        }
        // For parent that has children
        if ($args->walker->has_children) {
            $itemClasses[] = 'dropdown-toggle';
        }

        // Join classes into a string
        $itemClassNames = join(' ', $itemClasses);

        $attributes .= ( $args->walker->has_children ) ? ' class="'. $itemClassNames .'" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"' : 'class="'. $itemClassNames .'"';
        $itemOutput = $args->before;
        $itemOutput .= "<a $attributes>";
        $itemOutput .= $args->link_before . apply_filters( 'the_title', $item->title, $item->ID ) . $args->link_after;
        $itemOutput .= "</a>";
        $itemOutput .= $args->after;

        $output .= apply_filters ( 'walker_nav_menu_start_el', $itemOutput, $item, $depth, $args );
    }

    function end_el(&$output, $item, $depth = 0, $args = null)
    {
        parent::end_el($output, $item, $depth, $args); // TODO: Change the autogenerated stub
    }
}